MODEL_TYPE: "DrugBAN3D"

PATH:
  DATA_DIR: "datasets"
  RESULT_DIR: "result/DrugBAN3D_augmented_20250604_232654"
  CACHE_DIR: "/home/work/workspace/shi_shaoqun/snap/DrugBAN-main/cached_graphs_augmented"

# 数据集相关配置
DATA_3D:
  ROOT_DIR: "/home/work/workspace/shi_shaoqun/snap/3D_structure/bindingdb/train_pdb"
  LABEL_FILE: "/home/work/workspace/shi_shaoqun/snap/DrugBAN-main/augmented_labels/train_augmented.csv"
  DIS_THRESHOLD: 5.0
  NUM_WORKERS: 16 # 使用多线程加速数据加载
  TRAIN_FILE: "/home/work/workspace/shi_shaoqun/snap/3D_structure/bindingdb/train_csv/train_stratified.csv"
  VAL_FILE: "/home/work/workspace/shi_shaoqun/snap/3D_structure/bindingdb/train_csv/val_stratified.csv"
  TEST_FILE: "/home/work/workspace/shi_shaoqun/snap/3D_structure/bindingdb/train_csv/test_stratified.csv"

DATA:
  TRAIN_FILE: "/home/work/workspace/shi_shaoqun/snap/DrugBAN-main/augmented_labels/train_augmented.csv"
  VAL_FILE: "/home/work/workspace/shi_shaoqun/snap/DrugBAN-main/augmented_labels/valid_augmented.csv"
  TEST_FILE: "/home/work/workspace/shi_shaoqun/snap/DrugBAN-main/augmented_labels/test_augmented.csv"

TRAIN:
  D_LEARNING_RATE: 0.00018  # 最佳模型的学习率
  G_LEARNING_RATE: 0.0001   # 生成器学习率
  BATCH_SIZE: 32  # 批次大小
  D_STEPS_PER_G_STEP: 1
  RESUME_CHECKPOINT: ""
  EPOCH: 100  # 总训练轮数
  GRADIENT_ACCUMULATE_STEPS: 4  # 梯度累积步数
  GRADIENT_CLIP_NORM: 1.0  # 梯度裁剪阈值
  WEIGHT_DECAY: 0.0003  # 权重衰减值
  LABEL_SMOOTHING: 0.05  # 标签平滑参数
  POS_WEIGHT: 2.3  # 正样本权重

DRUG:
  ATOM_MAX: 50
  NODE_IN_FEATS: 35
  NODE_IN_EMBEDDING: 128
  PADDING: True
  HIDDEN_LAYERS: [128, 256, 256]  # 药物分子隐藏层结构

PROTEIN:
  SEQ_MAX: 1000
  EMBEDDING_DIM: 64
  PADDING: True
  NUM_FILTERS: [32, 64, 96]
  KERNEL_SIZE: [4, 8, 12]
  NODE_IN_FEATS: 35

EDGE_FEATS:
  intra_l: 17
  intra_p: 17
  inter_l2p: 11
  inter_p2l: 11

GNN:
  HIDDEN_DIM: 384  # GNN隐藏维度
  NUM_LAYERS: 4    # GNN层数

BCN:
  HEADS: 8  # 注意力头数量

DECODER:
  IN_DIM: 384
  HIDDEN_DIM: 512
  OUT_DIM: 128  # 解码器输出维度
  BINARY: 1
  DROPOUT: 0.5  # Dropout率

ADAPT:
  LAMBDA: 0.1
  USE_TARGET: False
  METHOD: None
  ENTROPY_LAMBDA: 1.0
  RANDOM_DIM: 512

COMET:
  USE: False
  PROJECT: "DrugBAN3D"
  WORKSPACE: "xsahbhc"
  TAG: "best_config"

SOLVER:
  MAX_EPOCH: 100
  BATCH_SIZE: 32
  USE_MIXED_PRECISION: False  # 不使用混合精度训练
  LR_SCHEDULER: True
  LR_SCHEDULER_TYPE: "plateau"  # 使用plateau学习率调度器
  LR_WARMUP_EPOCHS: 5  # 学习率预热轮数
  GRADIENT_CLIP_NORM: 1.0
  SEED: 42  # 随机种子

RESULT:
  OUTPUT_DIR: "result/DrugBAN3D_best_config"
  SAVE_MODEL: True
  SAVE_EACH_EPOCH: False
  SAVE_BEST_ONLY: True
  USE_STATE_DICT: True

# 早停配置
USE_EARLY_STOPPING: True
EARLY_STOPPING_PATIENCE: 15  # 早停耐心值

# 配置偏置校正
USE_BIAS_CORRECTION: True  # 启用偏置校正

# 损失函数配置
USE_FOCAL_LOSS: True  # 使用焦点损失
FOCAL_LOSS_GAMMA: 2.0
FOCAL_LOSS_ALPHA: 0.25

# 禁用的高级功能
USE_CONTRASTIVE_LOSS: False  # 不使用对比损失
USE_FEATURE_REGULARIZATION: False  # 不使用特征正则化

DA:
  USE: False
  METHOD: None
  INIT_EPOCH: 0
  LAMB_DA: 0.1
  RANDOM_LAYER: False
  ORIGINAL_RANDOM: False
  USE_ENTROPY: False 